Index file
rominana/trial-reviews pull request #1
Opened 2022-05-31 19:22 UTC by rominana

2022-05-31 19:27 UTC, rominana commented on index.html
> +       <div id="img-div">
### Semantic tags

- It would be better to use semantic tags in this case. Ex. `<main>`

2022-05-31 19:35 UTC, rominana reviewed
Hi @rominana! 
Good job so far! :fire:
There are some issues that you still need to work on to go to the next project but you are almost there! :rotating_light:

Let's take a look :eyes:

2022-05-31 19:50 UTC, Ismailco requested changes
### Hi @rominana,

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ Polite comments
✔️ Easy to understand comments

## Required Changes ♻️

- [ ] You don't always include an explanation for each requested change, please explain why you suggested the changes

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 15:10 UTC, rominana reviewed
### Hi @user,
Good job so far 👍🏼
There are some issues that you still need to work on to go to the next project but you are almost there!

**Changes Required** :recycle:

- [ ]  Please, add a title and description to your PR

- [ ]  Add a README.md file with the proper information about your project

- [ ]  Be sure to add your commits in the imperative form

- [ ]  Add linters for HTML and CSS so you can check your code

- [ ]  Remember to use the correct flow :

Please, check my comments below and make all required changes.

Submit for a re-review when you're done. :1st_place_medal: 

Thanks! :+1: :smile_cat:

2022-06-01 15:16 UTC, Munsa1 approved these changes
Hi @rominana , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Inline comments
:heavy_check_mark: respectful tone
:heavy_check_mark: Gve reason why

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 15:40 UTC, merged